[package]
name = "capnproto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.14.2"
capnp-futures = "0.14.1"
capnpc = "0.14.4"
chrono = "0.4.19"
clap = "2.33.3"
